### ISSUE TITLE
Errors with ListOpt{} when not specifying all values

### ISSUE THREAD

**Issue by klauern** [hbagdi/go-unsplash#17]
When using `ListOpt` to populate List Options, you need to specify **all** values for the options rather than each as you need them.  For instance, I have to specify `Page`, `PerPage` and `OrderBy` if I want it to work, otherwise it fails with `opt provided is not valid`:

```go
	photos, resp, err := u.Photos.Curated(&unsplash.ListOpt{
		OrderBy: unsplash.Popular,
	})
```
Will create an error

**Comment by hbagdi** [comment]
@klauern yes, that doesn't seem right.
I'll push a fix for this soon.

**Comment by hbagdi** [comment]
@klauern Reopen this if commit https://github.com/hbagdi/go-unsplash/commit/4ead243d914e62e05abd0f0a429f9dea4fbfb133 doesn't fix the problem
