### ISSUE TITLE
Paging through responses

### ISSUE THREAD

**Issue by hbagdi** [hbagdi/go-unsplash#7]
*Response gives info about paging but there is no mechanism to traverse multi-page results.

**Comment by hardikbagdi** [comment]
There is no direct mechanism to traverse through the pages.
One can read the response object and then give the next page as a list option that would work but a simpler approach would be much more helpful.

**Comment by hardikbagdi** [comment]
The "link" header has hrefs to the next page. This could be saved and a request could be fired on them.
Need to think more on how to design this.

**Comment by hbagdi** [comment]
Pagination like go-github does is a good enough interface for now. Will revisit in future if needed.
https://godoc.org/github.com/google/go-github/github#hdr-Pagination
